target: ./section-1-practice-questions.tex
	pdflatex ./section-1-practice-questions.tex
	rm ./section-1-practice-questions.log ./section-1-practice-questions.aux ./section-1-practice-questions.out
	firefox ./section-1-practice-questions.pdf
